# This workflow runs tests and linters.
name: check
on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.*"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.3
          args: "-v"

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      # Run tests in docker to mimic the production environment.
      - run: make docker-test
