# This workflow runs tests and linters.
name: Check
on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.*"
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          args: "-v"

  test:
    strategy:
      matrix:
        include:
          - os: "ubuntu-24.04"
            platform: "amd64"
          - os: "ubuntu-24.04-arm"
            platform: "arm64"
    name: Run tests on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # Run tests in docker to mimic the production environment.
      - run: make docker-test
