name: check
on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.*"
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: "-v"

  # TODO: use an alpine image to mimic the production environment?
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.*"
      - run: sudo apt-get install libvips-tools
      - run: curl https://rclone.org/install.sh | sudo bash
      - run: make test
