# This workflow runs tests and linters.
name: check
on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.*"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1
          args: "-v"

  # TODO: use an alpine image to mimic the production environment?
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.*"
      - run: sudo apt-get update && sudo apt-get install libvips-tools
      - run: curl https://rclone.org/install.sh | sudo bash
      - run: make test
