# This workflow builds a docker image and pushes it.
name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make docker-build
      - run: docker tag rview ghcr.io/shoshinnikita/rview:main
      - run: docker push ghcr.io/shoshinnikita/rview:main
      # Keep only the last 5 untagged images.
      - uses: actions/delete-package-versions@v5
        with:
          package-name: rview
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: "true"
