name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: make docker-build
      - run: docker tag rview ghcr.io/shoshinnikita/rview:main
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push ghcr.io/shoshinnikita/rview:main
